package fr.monopoly.backend.Models.Enumerations;

public enum CellName {

    // Names of the cells on the board
    BOULEVARD_DE_BELLEVILLE,
    RUE_LECOURBE,
    RUE_DE_VAUGIRARD,
    RUE_DE_COURCELLES,
    AVENUE_DE_LA_REPUBLIQUE,
    BOULEVARD_DE_LA_VILLETTE,
    AVENUE_DE_NEUILLY,
    RUE_DE_PARADIS,
    AVENUE_DE_MOZART,
    BOULEVARD_SAINT_MICHEL,
    PLACE_PIGALLE,
    AVENUE_MATIGNON,
    BOULEVARD_MALESHERBES,
    AVENUE_HENRI_MARTIN,
    FAUBOURG_SAINT_HONORE,
    PLACE_DE_LA_BOURSE,
    RUE_LA_FAYETTE,
    AVENUE_DE_BRETEUIL,
    AVENUE_FOCH,
    BOULEVARD_DES_CAPUCINES,
    AVENUE_DES_CHAMPS_ELYSEES,
    RUE_DE_LA_PAIX,

    GARE_MONTPARNASSE,
    GARE_DE_LYON,
    GARE_DU_NORD,
    GARE_SAINT_LAZARE,

    DEPART,
    PRISON,
    VISITE_DE_PRISON,
    PARC_GRATUIT,

    CHANCE,
    COMMUNAUTE,

    IMPOT_SUR_LE_REVENU,
    TAXE_DE_LUXE,
    COMPAGNIE_DES_EAUX,
    COMPAGNIE_DE_DISTIBUTION_ELECTRIQUE




}
